#index:
#    path: /
#    controller: App\Controller\DefaultController::index
articles_list:
    path: /
    controller: App\Controller\ArticleController::getAll

article_detail:
  path: /article/{id}
  controller: App\Controller\ArticleController::getOne

article_creation:
  path: /create
  controller: App\Controller\ArticleController::create

article_edition:
  path: /article/{id}/edit
  controller: App\Controller\ArticleController::edit

article_delete:
  path: /article/{id}/delete
  controller: App\Controller\ArticleController::delete